config/routes.rb
Rails.application.routes.draw do
  root 'find_my_fibre#index'

  resources   :projects  do
    resources :switchgears do
      resources :otdfs, except: (:index) do
          resources :fibres, except: (:index)
      end
    end
    member do
      get :addusers
      get :removeuser
    end
  end

  devise_for  :users
  devise_for  :admins, controllers: { sessions: 'admin/sessions' }
  devise_for  :superadmins
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'

end

app/models/switchgear.rb
class Switchgear < ActiveRecord::Base
  belongs_to :project
  has_many :otdfs, dependent: :destroy
end

app/controllers/switchgears_controller.rb
class SwitchgearsController < ApplicationController

  def show
    @switchgear = Switchgear.find(params[:id])
    @otdfs = @switchgear.otdfs.all
    @project = params[:project_id]
  end

  def destroy
    project = Project.find(params[:project_id])
    @switchgear = project.switchgears.find(params[:id])
    @switchgear.destroy
    respond_to do |format|
      format.html { redirect_to project_url(@project), notice: 'Otdf was successfully destroyed.' }
    end
  end
end

app/helpers/switchgears_helper.rb
module SwitchgearsHelper
end

app/views/switchgears/show.html.erb
<div class="row">
  <% @otdfs.each do |otdf| %>
    <div class="col-md-8">
      <div class="project_add">
        <p>
        Otdf size
        <%= otdf.size %><br />
        Otdf direct
        <%= otdf.direct %><br />
        <%= link_to "See Otdf" , project_switchgear_otdf_path(@project, @switchgear, otdf) %><br />
        <%= link_to 'Edit', edit_project_switchgear_otdf_path(@project, @switchgear, otdf) %><br />
        <%= link_to 'Destroy', project_switchgear_otdf_path(@project, @switchgear, otdf), method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div>
    </div>
  <% end %>
  <%= link_to 'Add new OTDF', new_project_switchgear_otdf_path(@project, @switchgear) %>
</div>