config/routes.rb
Rails.application.routes.draw do
  root 'find_my_fibre#index'

  resources   :projects  do
    resources :switchgears do
      resources :otdfs, except: (:index) do
          resources :fibres, except: (:index)
      end
    end
    member do
      get :addusers
      get :removeuser
    end
  end

  devise_for  :users
  devise_for  :admins, controllers: { sessions: 'admin/sessions' }
  devise_for  :superadmins
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'

end

app/controllers/find_my_fibre_controller.rb
class FindMyFibreController < ApplicationController
  def index
  end
end

app/helpers/find_my_fibre_helper.rb
module FindMyFibreHelper
end

app/views/find_my_fibre/index.html.erb
<% if current_admin %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="project_add">
        <h2><%= link_to("Creat new Project",  new_project_path) %>  </h1>
        <p> Creat your own passporting network</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="project_add">
        <h2><%= link_to("Show my Projects",  projects_path) %>  </h1>
        <p> See all Project what i`m created</p>
      </div>
    </div>
  </div>
<% elsif current_user %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="project_add">
        <% if current_user.project_id.present? %>
          <h2><%= link_to("Creat new Project",  project_path(id: current_user.project.id)) %>  </h1>
          <p> Creat your own passporting network</p>
        <% else %>
          <p> Ask Admin who you know to add you to project </p>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <div class="project_add">
        <h1>FindMyFibre</h1>
        <p>This application is for passporting fiber-optic network  </p>
        <p> If you want to access to creat you own network pleasa conntact me
          <a href="mailto:lach.szymon86@gmail.com">lach.szymon86@gmail.com</a>
        </p>
      </div>
    </div>
  </div>
<% end %>