config/routes.rb
Rails.application.routes.draw do
  root 'find_my_fibre#index'

  resources   :projects  do
    resources :switchgears do
      resources :otdfs, except: (:index) do
          resources :fibres, except: (:index)
      end
    end
    member do
      get :addusers
      get :removeuser
    end
  end

  devise_for  :users
  devise_for  :admins, controllers: { sessions: 'admin/sessions' }
  devise_for  :superadmins
  mount RailsAdmin::Engine => '/superadmin', as: 'rails_admin'

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :switchgears, dependent: :destroy
  has_many :users
  belongs_to :admin
  accepts_nested_attributes_for :switchgears, reject_if: lambda { |a| a[:description].blank? }, allow_destroy: true
  accepts_nested_attributes_for :users

  def form_switchgears
    self.switchgears.build
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update, :new, :create, :destroy, :index]
  before_action :find_project_by_admin, only: [:edit, :update, :destroy]

  def addusers
    @project = set_project
    @project.users << User.find(params[:user_id])
    respond_to do |format|
      format.html { redirect_to @project, :notice => 'Added.' }
    end
  end

  def removeuser
    @project = set_project
    @user = User.find(params[:user_id])
    if @user
      @project.users.delete(@user)
    end
    respond_to do |format|
      format.html { redirect_to @project, notice: 'User was successfully removed from Project' }
    end
  end

  def index
    @projects = current_admin.projects.all
  end

  def show
    @users = User.where(project_id: nil)
    @usersadd = @project.users.all
    @switchgears = @project.switchgears.all
  end

  def new
    @project = Project.new
    @project.form_switchgears
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.admin = current_admin
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :admin_id, switchgears_attributes:[:id, :description,:_destroy])
  end

  def find_project_by_admin
    @project = current_admin.projects.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
  <%= f.fields_for :switchgears do |builder| %>
    <%= render "switchgear_fields", f: builder %>
  <% end %>
  <%= link_to_add_switchgears "Add switchgears", f, :switchgears %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_switchgear_fields.html.erb
<fieldset>
  <%= f.label :description, "SwitchgearFiber" %><br />
  <%= f.text_area :description %> <br />
  <%= f.hidden_field :_destroy%>
  <%= link_to "[remove]", '#', class: "remove_switchgear" %>
</fieldset>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="project_add">
      <h1>Listing Projects</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= project.name %></td>
              <td><%= link_to 'Show', project %></td>
              <td><%= link_to 'Edit', edit_project_path(project) %></td>
              <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table><br />
      <%= link_to 'New Project', new_project_path %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <div class="project_add">
      <h1>New Project</h1>
      <%= render 'form' %>
      <%= link_to 'Back', projects_path %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="project_add">
      <p id="notice"><%= notice %></p>
      <p>
      <strong>Name:</strong>
      <%= @project.name %>
      </p>
      <p>
      <strong>Admin:</strong>
      <%= @project.admin %>
      </p>
    </div>
  </div>
</div>
<% if current_admin %>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="project_add">
      <table><h1> User</h1>
        <thead>
          <tr>
            <th>Id</th>
            <th>Email</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <%= user.email %> <%= link_to 'Add user', addusers_project_path(@project, user_id: user.id) %><br />
          <% end %>
        </tbody>
        <tbody>
          <% @usersadd.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.email %></td>
              <td><%= link_to 'Remove user',  removeuser_project_path(@project, user_id: user.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <div class="project_add">
      <table><h1>Switchgear </h1>
        <thead>
          <tr>
            <th>Description</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @switchgears.each do |switchgear| %>
            <tr>
              <td><%= switchgear.description %></td>
              <td><%= link_to("Show" , project_switchgear_path(switchgear.project, switchgear)) %></td>
              <td><%= link_to 'Destroy', [switchgear.project, switchgear], :confirm => 'Are you sure?', :method => :delete %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>